name: example
on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  check_action:
    runs-on: ubuntu-latest
    outputs:
      action_name: ${{ steps.define_type.outputs.action_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Define type
        id: define_type
        run: |
          echo "::set-output name=action_name::${{ github.event.action }}"

  main:
    needs: [check_action]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show action name
        run: |
          if [ ${{ needs.check_action.outputs.action_name }} = 'labeled' ]; then
            echo "This workflow was triggered by 'labeled'"
          else
            echo "This workflow was triggered by 'synchronize'"
          fi

  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"