name: example
on:
  pull_request:
    types:
      - labeled
      - synchronize # default
jobs:
  labeled_job:
    if: contains(github.event.pull_request.labels.*.name, 'trigger')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do something
        id: do-something
        run: |
          echo "::set-output name=hoge::piyo"
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
      - name: Do something02
        run: echo ${{ steps.do-something.outputs.hoge }}

  # synchronize_job:
  #   if: contains(github.event.pull_request.labels.*.name, 'trigger')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Do something
  #       id: do-something
  #       run: echo "::set-output name=hoge::piyo"
  #     - name: Do something02
  #       run: echo ${{ steps.do-something.outputs.hoge }}

  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"