name: example
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do something
        run: echo "hello"