name: example
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Do something
        id: do-something
        run: echo "::set-output name=hoge::piyo"
      - name: Do something02
        run: echo ${{ steps.do-something.outputs.hoge }}