name: push
on:
  [push]

jobs:
  get_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get_hoge
        id: get_hoge
        run: |
          hoge=$(cat config.json | jq .hoge)
          echo $hoge