name: push
on:
  [push]

jobs:
  get_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get_hoge
        id: get_hoge
        run: |
          date
          hoge=$(cat config.json | jq .hoge)
          echo "::set-output name=hoge::$hoge"
      - name: echo_value
        run: |
          echo ${{ steps.get_hoge.outputs.hoge }}