name: push
on:
  [push]

jobs:
  test_jq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CONFIG: $(cat config.json | jq .hoge)
        run: |
          echo $CONFIG