name: Slash Command
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash command dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          commands: |
            fruit
          dispatch-type: workflow
      - name: Echo something
        run: |
          echo "${{ github.event.repository.full_name }}#${{ github.event.issue.number }}"

